# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalendarWidget.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(1108, 586)
        self.groupBox = QtWidgets.QGroupBox(Frame)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 481, 331))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 461, 291))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.gridLayoutWidget)
        self.calendarWidget.setSelectedDate(QtCore.QDate(2017, 5, 30))
        self.calendarWidget.setGridVisible(False)
        self.calendarWidget.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.calendarWidget.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.ISOWeekNumbers)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(True)
        self.calendarWidget.setDateEditAcceptDelay(1500)
        self.calendarWidget.setObjectName("calendarWidget")
        self.gridLayout.addWidget(self.calendarWidget, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Frame)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 350, 481, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget_30 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_30.setGeometry(QtCore.QRect(240, 40, 231, 31))
        self.verticalLayoutWidget_30.setObjectName("verticalLayoutWidget_30")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_30)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.verticalLayoutWidget_30)
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(1900, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.verticalLayout_28.addWidget(self.dateEdit_2)
        self.verticalLayoutWidget_31 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_31.setGeometry(QtCore.QRect(240, 80, 231, 31))
        self.verticalLayoutWidget_31.setObjectName("verticalLayoutWidget_31")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_31)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget_31)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2017, 5, 30), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.MonthSection)
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setObjectName("dateEdit")
        self.verticalLayout_29.addWidget(self.dateEdit)
        self.verticalLayoutWidget_32 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_32.setGeometry(QtCore.QRect(240, 120, 231, 31))
        self.verticalLayoutWidget_32.setObjectName("verticalLayoutWidget_32")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_32)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.dateEdit_3 = QtWidgets.QDateEdit(self.verticalLayoutWidget_32)
        self.dateEdit_3.setDateTime(QtCore.QDateTime(QtCore.QDate(3000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_3.setObjectName("dateEdit_3")
        self.verticalLayout_30.addWidget(self.dateEdit_3)
        self.verticalLayoutWidget_33 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_33.setGeometry(QtCore.QRect(10, 40, 121, 31))
        self.verticalLayoutWidget_33.setObjectName("verticalLayoutWidget_33")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_33)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_33)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_31.addWidget(self.label_23)
        self.verticalLayoutWidget_34 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_34.setGeometry(QtCore.QRect(10, 80, 121, 31))
        self.verticalLayoutWidget_34.setObjectName("verticalLayoutWidget_34")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_34)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_34)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_32.addWidget(self.label_24)
        self.verticalLayoutWidget_35 = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget_35.setGeometry(QtCore.QRect(10, 120, 121, 31))
        self.verticalLayoutWidget_35.setObjectName("verticalLayoutWidget_35")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_35)
        self.verticalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_25 = QtWidgets.QLabel(self.verticalLayoutWidget_35)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_33.addWidget(self.label_25)
        self.groupBox_3 = QtWidgets.QGroupBox(Frame)
        self.groupBox_3.setGeometry(QtCore.QRect(510, 10, 581, 331))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 170, 141, 31))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.checkBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_5)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_5.addWidget(self.checkBox)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(440, 170, 131, 31))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.checkBox_2 = QtWidgets.QCheckBox(self.verticalLayoutWidget_6)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_6.addWidget(self.checkBox_2)
        self.verticalLayoutWidget_19 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(10, 40, 141, 31))
        self.verticalLayoutWidget_19.setObjectName("verticalLayoutWidget_19")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_19)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_19)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_19.addWidget(self.label_18)
        self.verticalLayoutWidget_20 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(150, 40, 411, 31))
        self.verticalLayoutWidget_20.setObjectName("verticalLayoutWidget_20")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_20)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget_20)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_10.addWidget(self.comboBox_2)
        self.verticalLayoutWidget_21 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_21.setGeometry(QtCore.QRect(10, 80, 141, 31))
        self.verticalLayoutWidget_21.setObjectName("verticalLayoutWidget_21")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_21)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_21)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_20.addWidget(self.label_19)
        self.verticalLayoutWidget_22 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_22.setGeometry(QtCore.QRect(10, 120, 141, 31))
        self.verticalLayoutWidget_22.setObjectName("verticalLayoutWidget_22")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_22)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_22)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_21.addWidget(self.label_20)
        self.verticalLayoutWidget_23 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_23.setGeometry(QtCore.QRect(150, 80, 411, 31))
        self.verticalLayoutWidget_23.setObjectName("verticalLayoutWidget_23")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_23)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.comboBox_6 = QtWidgets.QComboBox(self.verticalLayoutWidget_23)
        self.comboBox_6.setEditable(False)
        self.comboBox_6.setDuplicatesEnabled(False)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.verticalLayout_11.addWidget(self.comboBox_6)
        self.verticalLayoutWidget_24 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_24.setGeometry(QtCore.QRect(150, 120, 411, 31))
        self.verticalLayoutWidget_24.setObjectName("verticalLayoutWidget_24")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_24)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.comboBox_9 = QtWidgets.QComboBox(self.verticalLayoutWidget_24)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.verticalLayout_22.addWidget(self.comboBox_9)
        self.verticalLayoutWidget_25 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_25.setGeometry(QtCore.QRect(10, 220, 141, 31))
        self.verticalLayoutWidget_25.setObjectName("verticalLayoutWidget_25")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_25)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_25)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_23.addWidget(self.label_21)
        self.verticalLayoutWidget_26 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_26.setGeometry(QtCore.QRect(150, 220, 411, 31))
        self.verticalLayoutWidget_26.setObjectName("verticalLayoutWidget_26")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_26)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.comboBox_10 = QtWidgets.QComboBox(self.verticalLayoutWidget_26)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.verticalLayout_24.addWidget(self.comboBox_10)
        self.verticalLayoutWidget_27 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_27.setGeometry(QtCore.QRect(10, 270, 141, 31))
        self.verticalLayoutWidget_27.setObjectName("verticalLayoutWidget_27")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_27)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_27)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_25.addWidget(self.label_22)
        self.verticalLayoutWidget_28 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_28.setGeometry(QtCore.QRect(150, 270, 411, 31))
        self.verticalLayoutWidget_28.setObjectName("verticalLayoutWidget_28")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_28)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.comboBox_8 = QtWidgets.QComboBox(self.verticalLayoutWidget_28)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.verticalLayout_26.addWidget(self.comboBox_8)
        self.groupBox_4 = QtWidgets.QGroupBox(Frame)
        self.groupBox_4.setGeometry(QtCore.QRect(510, 350, 581, 171))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_12 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_12.setGeometry(QtCore.QRect(460, 130, 111, 31))
        self.verticalLayoutWidget_12.setObjectName("verticalLayoutWidget_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_12)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.checkBox_4 = QtWidgets.QCheckBox(self.verticalLayoutWidget_12)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_13.addWidget(self.checkBox_4)
        self.verticalLayoutWidget_13 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_13.setGeometry(QtCore.QRect(270, 40, 291, 31))
        self.verticalLayoutWidget_13.setObjectName("verticalLayoutWidget_13")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_13)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.comboBox_11 = QtWidgets.QComboBox(self.verticalLayoutWidget_13)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.verticalLayout_9.addWidget(self.comboBox_11)
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(10, 70, 160, 31))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_15.addWidget(self.label_16)
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(270, 70, 291, 31))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.comboBox_12 = QtWidgets.QComboBox(self.verticalLayoutWidget_16)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.verticalLayout_16.addWidget(self.comboBox_12)
        self.verticalLayoutWidget_17 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(10, 100, 160, 31))
        self.verticalLayoutWidget_17.setObjectName("verticalLayoutWidget_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_17)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_17.addWidget(self.label_17)
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(270, 100, 291, 31))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.comboBox_13 = QtWidgets.QComboBox(self.verticalLayoutWidget_18)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.verticalLayout_18.addWidget(self.comboBox_13)
        self.verticalLayoutWidget_29 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_29.setGeometry(QtCore.QRect(10, 130, 160, 31))
        self.verticalLayoutWidget_29.setObjectName("verticalLayoutWidget_29")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_29)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.checkBox_3 = QtWidgets.QCheckBox(self.verticalLayoutWidget_29)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_27.addWidget(self.checkBox_3)
        self.verticalLayoutWidget_36 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_36.setGeometry(QtCore.QRect(10, 40, 160, 31))
        self.verticalLayoutWidget_36.setObjectName("verticalLayoutWidget_36")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_36)
        self.verticalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_36)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_34.addWidget(self.label_10)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Calendar Widget"))
        self.groupBox.setTitle(_translate("Frame", "Preview"))
        self.groupBox_2.setTitle(_translate("Frame", "Dates"))
        self.dateEdit_2.setDisplayFormat(_translate("Frame", "M/d/yyyy"))
        self.dateEdit.setDisplayFormat(_translate("Frame", "M/d/yyyy"))
        self.dateEdit_3.setDisplayFormat(_translate("Frame", "M/d/yyyy"))
        self.label_23.setText(_translate("Frame", "Minumum Date :"))
        self.label_24.setText(_translate("Frame", "Current Date :"))
        self.label_25.setText(_translate("Frame", "Maximum Date :"))
        self.groupBox_3.setTitle(_translate("Frame", "General Option"))
        self.checkBox.setText(_translate("Frame", "Grid"))
        self.checkBox_2.setText(_translate("Frame", "Navigation bar"))
        self.label_18.setText(_translate("Frame", "Locale"))
        self.comboBox_2.setItemText(0, _translate("Frame", "German/Germany"))
        self.comboBox_2.setItemText(1, _translate("Frame", "Inggris"))
        self.comboBox_2.setItemText(2, _translate("Frame", "Jepang"))
        self.comboBox_2.setItemText(3, _translate("Frame", "Indonesia"))
        self.label_19.setText(_translate("Frame", "Week starts on :"))
        self.label_20.setText(_translate("Frame", "Selection mode :"))
        self.comboBox_6.setItemText(0, _translate("Frame", "Sunday"))
        self.comboBox_6.setItemText(1, _translate("Frame", "Monday"))
        self.comboBox_6.setItemText(2, _translate("Frame", "Tuesday"))
        self.comboBox_6.setItemText(3, _translate("Frame", "Wednesday"))
        self.comboBox_6.setItemText(4, _translate("Frame", "Thursday"))
        self.comboBox_6.setItemText(5, _translate("Frame", "Friday"))
        self.comboBox_6.setItemText(6, _translate("Frame", "Saturday"))
        self.comboBox_9.setItemText(0, _translate("Frame", "Single selection"))
        self.comboBox_9.setItemText(1, _translate("Frame", "Duo selection"))
        self.label_21.setText(_translate("Frame", "Horizontal header : "))
        self.comboBox_10.setItemText(0, _translate("Frame", "Short day names"))
        self.comboBox_10.setItemText(1, _translate("Frame", "Long day names"))
        self.label_22.setText(_translate("Frame", "Selection mode :"))
        self.comboBox_8.setItemText(0, _translate("Frame", "ISO week numbers"))
        self.groupBox_4.setTitle(_translate("Frame", "Text Format"))
        self.checkBox_4.setText(_translate("Frame", "May 1 in red"))
        self.comboBox_11.setItemText(0, _translate("Frame", "Black"))
        self.comboBox_11.setItemText(1, _translate("Frame", "Red"))
        self.comboBox_11.setItemText(2, _translate("Frame", "White"))
        self.label_16.setText(_translate("Frame", "Weekend color :"))
        self.comboBox_12.setItemText(0, _translate("Frame", "Black"))
        self.comboBox_12.setItemText(1, _translate("Frame", "Red"))
        self.comboBox_12.setItemText(2, _translate("Frame", "White"))
        self.label_17.setText(_translate("Frame", "Header text :"))
        self.comboBox_13.setItemText(0, _translate("Frame", "Bold"))
        self.comboBox_13.setItemText(1, _translate("Frame", "Thin"))
        self.checkBox_3.setText(_translate("Frame", "First friday in blue"))
        self.label_10.setText(_translate("Frame", "Weekday color :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Frame = QtWidgets.QFrame()
    ui = Ui_Frame()
    ui.setupUi(Frame)
    Frame.show()
    sys.exit(app.exec_())
